#General settings
[general]
	#modpackProjectID is now deprecated and will be removed soon
	# Default: 0
	# Range: > 0
	modpackProjectID = 444395
	#The name of the modpack
	modpackName = "Create on a Potato PC: Ultimate Edition"
	#The version of the modpack
	modpackVersion = "1.21.1-1.0.0"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false
